name: Robot Amazon Quotidien

on:
  schedule:
    # Tous les jours à 06:00 UTC (soit 07h00 ou 08h00 en France selon la saison)
    - cron: '0 6 * * *'
  workflow_dispatch: # Bouton pour le lancer à la main

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Récupérer le code du robot
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # SOLUTION : Utilisation de l'outil officiel pour installer Chrome proprement
    - name: Installer Google Chrome et son Driver automatiquement
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Installer les extensions Python
      run: |
        pip install requests beautifulsoup4 pandas openpyxl selenium webdriver-manager

    - name: Lancer le Robot !
      run: python robot.py

    - name: Sauvegarder le fichier Excel sur GitHub
      run: |
        git config --global user.name 'Robot Amazon'
        git config --global user.email 'bot@amazon.com'
        git add *.xlsx
        git commit -m "Mise à jour automatique des Bestsellers" || exit 0
        git push origin main
