name: Robot Amazon Quotidien

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Récupérer le code du robot
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installer Google Chrome et son Driver automatiquement
      uses: browser-actions/setup-chrome@v1.7.2
      with:
        chrome-version: stable

    - name: Installer les extensions Python
      run: |
        pip install requests beautifulsoup4 pandas openpyxl selenium webdriver-manager

    - name: Lancer la Phase 1 (Classement des 100 Bestsellers)
      run: python robot.py

    - name: Lancer la Phase 2 (Aspiration profonde des fiches produits)
      run: python details_produits.py

    - name: Sauvegarder le fichier Excel sur GitHub
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      run: |
        git config --global user.name 'Robot Amazon'
        git config --global user.email 'bot@amazon.com'
        git config --global core.autocrlf false
        git add historique_bestsellers.xlsx
        git commit -m "Mise à jour automatique des Bestsellers et Fiches Produits" || exit 0
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $BRANCH_NAME --force
